[theme]
base="dark"              
primaryColor="#00FFAA"          
backgroundColor="#0E1117"         
secondaryBackgroundColor="#1A1D23"
textColor="#FFFFFF"               
font="monospace"                  

[client]
toolbarMode = "minimal"     


